### ISSUE TITLE
Fire TV Stick 4K: Dolby Vision content without picture or crash

### ISSUE THREAD

**Issue by infinity85** [CastagnaIT/plugin.video.netflix#410]
Hi there and happy new year,

I'm running a Fire TV Stick 4k on last update FireOS and the most recent official Kodi version for android: http://mirrors.kodi.tv/releases/android/arm/kodi-18.5-Leia-armeabi-v7a.apk

The issue is that after following all instructions to get Dolby Vision support, all Dolby Vision content either crashes the Kodi app upon pressing "play" or it would start only Audio without corresponding Video, so no Dolby Vision, not even any Video stream. Non-DV-content would play fine in 4k.
- I enabled HEVC and Dolby Vision in your Addon
- I enabled HDCP override in Inputstream Addon
- I even set Kodi to 3840 × 2160 and 23,976 refresh rate.
- The debug log (verbose) can be found here:
[Verbose Debug Log](https://paste.kodi.tv/xeheziqume.kodi)

Explanation to the debug log: 
1. Started Kodi App
2. I started an episode of  Stranger Things Season 2 (**which has 4K and Dolby Vision**)
3. The Episode starts with only Audio and Kodi then displays only the Cover as if It were an audio file or so. So no video settings available
4. I stopped the playback
5. As cross-check I started an Episode of Stranger Things Season 1, which has **_no_ Dolby Vision**, but is also 4K. This episode plays just fine.

Result: Dolby Vision wasn't triggered, actually there was no video at all if Dolby Vision was involved. If using official Netflix app on Fire TV, Dolby Vision gets triggered and plays fine, but is limited to 1080p60 playback, so no UHD.

I also tried the recent Kodi nightly:
kodi-20200101-15dcf22e-master-armeabi-v7a.apk
Result was the following error message: **"argument "init" for "GetKeyRequest" must be a string or a bytearray"**

The background:
since official Netflix App on FireTV does not support Auto frame rate matching, I wanted to use Netflix through Kodi to get Dolby Vision Content outputted in 4K Dolby Vision on my LG OLED 55C6 in native refresh rate. Remark: The 2016 LG OLEDs are limited to Dolby Vision at max. 2160p30, so for the lack of auto frame rate matching in official Netflix app, the FireTV GUI cannot/won't run in 4k in Netflix on my FireTV, because 4k FireTV UI would mean that it is 2160p60, which would exceed Dolby Vision supported modes. Hence Amazon or Netflix or whoever limits my FireTV to 1080p60 in its user interface, which in turn limits all Netflix Dolby Vision content to 1080p (so no 2160 UHD). Though, since nearly all 2160p Dolby Vision content is 23,976 fps/s anyway, that 2160p30 DV limit would not be exceeded, thus with auto frame rate switching support, netflix could actually play all DV content in 4K with DV, but netflix decided to avoid auto frame rate switching/matching. Amazon prime does it fine and the result is that on amazon prime video Tom Clancys Jack Ryan 1st season switches to 2160p24 Dolby Vision just fine.

If I missed to provide some helpful information, please let me know!

I wish you all a great start into the new year

**Comment by CastagnaIT** [comment]
thank you for the detailed explanation, happy new year also to you

i have a bad news dolby vision it has been fixed only on Kodi 19 (so in Kodi 18 not work)

if you want use dobly vision you can try use Kodi 19 (matrix)
but (to now) with it you have to install the Daily Build version of the nf addon

Unfortunately Matrix is currently NOT stable
and could cause other unexpected problems

I will not currently provide regular support for Kodi19 Matrix issues until it enters the Beta phase
I do not recommend the use, but if you want you can test it

**Comment by sukhish** [comment]
Thanks for the clarification, will look forward to matrix releases in future. Thanks.

**Comment by roenthomas** [comment]
It's funny, I can pick from the following:

1. Dolby Vision, but no Atmos and no auto refresh rate switching with Netflix App for Fire TV
2. HDR with Atmos and auto refresh rate switching, but no Dolby Vision with Netflix Add On for Kodi 18
3. Dolby Vision with Atmos and auto refresh rate switching, but lack of stability with Kodi 19 Nightly.

So close, but yet so far....

**Comment by kropen** [comment]
I have FireTV 4K with the latest update - fire Tv OS 6.2.8.0. I have Netflix Premium. I installed Kodi Matrix and the corresponding version of the Netflix Plugin for Kodi. I have the audio pass-through set. I still don't get Atoms. I can only see Dolby Digital 2.0. Wanted to check if Atmos works on Fire TV stick 4k. Any help much appriciated.

**Comment by CastagnaIT** [comment]
These are the full instructions: [how-to-enable-dolby-atmos](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#how-to-enable-dolby-atmos)
