### ISSUE TITLE
Typeerror when Syncing library to MyList

### ISSUE THREAD

**Issue by mobamoba** [CastagnaIT/plugin.video.netflix#695]
#### Your Environment
- Netflix add-on version: 1.40
- Operating system version/name: Coreelec 9.23
- Device model:  Odroid N2

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Perform full sync of Kodi library to My List fails with a Typeerror. (I accidentally reported this to a Closed report so am opening a new one.)

### Debug log
`ERROR: [plugin.video.netflix (0)] IPC callback raised exception: make_return_call() got an unexpected keyword argument 'ignore_update_lolomo_data' 2020-06-12 06:58:54.855 T:2855035776 ERROR: [plugin.video.netflix (0)] Traceback (most recent call last): File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 185, in make_return_call result = call(instance, func, data) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 209, in call return func(instance) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/directorybuilder/dir_builder.py", line 151, in get_mylist_videoids_profile_switch video_list = self.req_datatype_video_list_full('mylist', True) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/directorybuilder/dir_builder_requests.py", line 245, in req_datatype_video_list_full path_response = self.netflix_session._perpetual_path_request_switch_profiles(**call_args) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 37, in ensure_login return func(*args, **kwargs) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 138, in _perpetual_path_request_switch_profiles self.activate_profile(mylist_profile_guid, ignore_update_lolomo_data=True) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper return func(*args, **kwargs)

`

**Comment by CastagnaIT** [comment]
this is already fixed

**Comment by mobamoba** [comment]
I literally just got that error 20 minutes ago. I tried deleting and reinstalling the plugin and it happened again. Is there something else I can provide you with to help debug because it's still present in 1.40?

**Comment by CastagnaIT** [comment]
you mean the test version provided here https://github.com/CastagnaIT/plugin.video.netflix/issues/678 doesn't work?

jokerigno user said that all is ok

**Comment by mobamoba** [comment]
I thought that was 1.40 and not a test version. Just tried & it works - apologies for the misunderstanding.
