### ISSUE TITLE
No longer able to pass search query directly via plugin:// URI

### ISSUE THREAD

**Issue by jurialmunkey** [CastagnaIT/plugin.video.netflix#855]
#### Your Environment
- Netflix add-on version: 1.9.0
- Operating system version/name: Win 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
Previously the plugin allowed passing the title query directly in the plugin URI -- e.g. 
`plugin://plugin.video.netflix/directory/search/search/Stranger Things/`

This approach allows JSON-RPC `files.getdirectory` method to retrieve results. JSON-RPC is used for interacting with Kodi via a web interface and also via TMDbHelper

In recent versions (started in 1.8.0 I believe), passing the query directly to the plugin URI stopped working. The only option was to use the `directory/search/search/add/` path which is a problem for a web interface because it requires interacting with an onscreen keyboard (which you can't see in the web interface).

Even with this change, it was still possible for TMDbHelper to work around this limitation by passing text to the dialog using JSON-RPC `Input.SendText` method.

However, now even that approach doesn't work and no results are returned via files.getdirectory method.

#### Expected behavior
Plugin allows passing search query directly into plugin:// URI and will return a normal Kodi directory of listitems.

#### Actual behavior
Plugin no longer allows passing search query directly. 

Even if `/search/add/` method is used, it returns no results via files.getdirectory method.

#### Steps to reproduce the behavior

Settings > Service Settings > Control > Allow remote control via HTTP
- Port 8080

With Kodi running on local machine. Send in browser:
`http://127.0.0.1:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22Files.GetDirectory%22,%22params%22:{%22directory%22:%22plugin://plugin.video.netflix/directory/search/search/add/%22}}`

In Kodi select "search by term" and then input "Stranger Things"

Returns no results (it should return the directory listing).
`{u'jsonrpc': u'2.0', u'id': 1, u'result': {u'limits': {u'start': 0, u'total': 0, u'end': 0}}}`

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
your is a feature request not a bug report
the add-on is not intended to be managed by a third party or through RPC

**Comment by jurialmunkey** [comment]
BTW the issue is because you end the directory without creating any listitems and instead rely on using `container.update` to call the path
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/navigation/directory_search.py#L98

You should be creating and adding the listitems from the search results before ending the directory rather than relying on container update to call a new directory.

**Comment by jurialmunkey** [comment]
All addons should work via JSON RPC. That's why I reported this as a bug.

**Comment by CastagnaIT** [comment]
the redirect is mandatory or the context menus will be broken

**Comment by CastagnaIT** [comment]
> All addons should work via JSON RPC. That's why I reported this as a bug.

this is wrong, 
because the RPC call is other thing that not concern Kodi routing navigation,
therefore its compatibility has never been taken into account in this addon development

**Comment by CastagnaIT** [comment]
if you have a better solution to fix the context menus without doing a redirect i can consider the changes

**Comment by jurialmunkey** [comment]
I think I have an idea. Are you able to tell me which context menu items don't work so I'm able to test my changes?

**Comment by CastagnaIT** [comment]
are all the contextmenus that use container refresh are under:
navigation/library.py
navigation/actions.py

to test you could take one, example "def my_list" method
keep only the container_refresh() code and comment all other code inside the method

when in a tvshow or movie and you select "add to mylist",
the search dialog do not have to start again

**Comment by jurialmunkey** [comment]
^^^ That fixes the issue with JSON RPC not returning results. I also fixed the issue where pressing back after search add/clear would retrigger it.

**Comment by corus87** [comment]
@jurialmunkey  Hi, I also used to use `plugin://plugin.video.netflix/directory/search/search/Stranger Things/` to perform a search. As far as I understand with your [PR](https://github.com/CastagnaIT/plugin.video.netflix/pull/856) you fixed the issue, but I'm still not able to perform a search.

Is there a new plugin url I have to use now?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Hi, I also used to use `plugin://plugin.video.netflix/directory/search/search/Stranger Things/` to perform a search. As far as I understand with your [PR](https://github.com/CastagnaIT/plugin.video.netflix/pull/856) you fixed the issue, but I'm still not able to perform a search.
> 
> Is there a new plugin url I have to use now?

My PR doesn't add the ability to pass search queries directly via the URI, it only fixes the directory items return so that the results will display via JSON-RPC.

The RPC method still needs to use Input.SendText to fill the on-screen keyboard with the query. There's currently no method in the Netflix plugin to allow passing search queries via the URI.

**Comment by corus87** [comment]
Thanks for clarify @jurialmunkey

**Comment by drinfernoo** [comment]
@CastagnaIT, is there any possibility of readding the ability to pass queries directly via a URI?
